<template>
  <div class="min-h-screen bg-gray-100 dark:bg-gray-900 py-12">
    <div class="container mx-auto px-4 sm:px-6 lg:px-8">
      <div class="text-center mb-10">
        <h1
          class="text-5xl md:text-6xl font-extrabold tracking-tight text-gray-900 dark:text-white"
        >
          Jobs by Skill
        </h1>
        <p class="mt-4 text-xl text-gray-600 dark:text-gray-400">
          Explore job opportunities based on specific IT skills.
        </p>
      </div>

      <div class="bg-white dark:bg-gray-800 shadow-xl rounded-lg p-8 sm:p-10 lg:p-12">
        <div
          class="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 xl:grid-cols-6 gap-x-4 gap-y-3"
        >
          <RouterLink
            v-for="skill in itSkills"
            :key="skill"
            :to="`/jobs?skill=${skill}`"
            class="flex items-center justify-center p-2 rounded-md bg-gray-50 dark:bg-gray-700 hover:bg-green-100 dark:hover:bg-green-800 transition-colors duration-200 text-gray-800 dark:text-gray-200 hover:text-green-700 dark:hover:text-green-200 text-base font-medium whitespace-nowrap overflow-hidden text-ellipsis"
          >
            {{ skill }}
          </RouterLink>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { RouterLink } from 'vue-router' // Đảm bảo bạn đã import RouterLink

const itSkills = ref([
  '3ds Max',
  'ABAP',
  'A/B testing',
  'Adobe',
  'Adobe Illustrator',
  'Adobe Photoshop',
  'Adobe XD',
  'Agile',
  'AI',
  'Android',
  'Android studio',
  'Angular',
  'AngularJS',
  'Ansible',
  'Apache Airflow',
  'Apache Spark',
  'API',
  'Appium',
  'ASPICE',
  'ASP.NET',
  'AutoCAD',
  'Automation Test',
  'AWS',
  'AWS CloudFormation',
  'AWS Lambda',
  'Axure',
  'Azure',
  'Balsamiq',
  'Big Data',
  'Black box testing',
  'BLE',
  'Blockchain',
  'BRD',
  'Bridge Project Management',
  'Burp Suite',
  'Business Analysis',
  'Business Intelligence',
  'C#',
  'C++',
  'CI/CD',
  'Cisco',
  'C language',
  'Clean Architecture',
  'Cloud',
  'Cloud-native Architecture',
  'Cloud Security',
  'Cocos',
  'Cocos2d-x',
  'CompTIA Security+',
  'Computer Vision',
  'Container Security',
  'CRM',
  'Cryptography',
  'CSS',
  'CSS 3',
  'Cucumber',
  'Cybersecurity',
  'Cypress',
  'Dart',
  'Data Analysis',
  'Database',
  'Databricks',
  'Data cleaning',
  'Data-driven',
  'Data Engineer',
  'Data mining',
  'Data modeling',
  'Data Science',
  'Data Warehousing',
  'DBA',
  'DBT',
  'Deep Learning',
  'Design',
  'Design Systems',
  'DevOps',
  'DevSecOps',
  'Django',
  'Docker',
  'Domain-Driven Design',
  'Ec-cube',
  'EDR',
  'Elasticsearch',
  'ELT',
  'Embedded',
  'Embedded C',
  'English',
  'Enterprise Architecture',
  'Entity Framework',
  'ERP',
  'ETL',
  'Express',
  'ExpressJS',
  'F#',
  'FastAPI',
  'Figma',
  'Firebase',
  'Firewall',
  'Firmware',
  'Flask',
  'Flutter',
  'Fullstack',
  'Games',
  'GCP',
  'Generative AI',
  'Git',
  'GitHub',
  'GitHub Actions',
  'Golang',
  'Google BigQuery',
  'Google Cloud',
  'Google Cloud SQL',
  'Governance, Risk & Compliance',
  'Grafana',
  'GraphQL',
  'Groovy',
  'Hadoop',
  'Hardware Design',
  'Hardware Troubleshooting',
  'Helm',
  'Hibernate',
  'HPE LoadRunner',
  'HTML5',
  'IDS/IPS',
  'Illustrator',
  'Information Security',
  'Integration test',
  'iOS',
  'IoT',
  'ISO 27001',
  'IT Audit',
  'IT Communication/Translation',
  'IT Governance',
  'ITIL Foundation',
  'IT Support',
  'J2EE',
  'Japanese',
  'Japanese IT Communication',
  'Java',
  'JavaScript',
  'Jenkins',
  'Jira',
  'Jmeter',
  'JQuery',
  'JSON',
  'Juniper',
  'Kafka',
  'Kanban',
  'Katalon',
  'Koa',
  'Korean',
  'Kotlin',
  'Kubernetes',
  'Laravel',
  'Leadership',
  'LINQ',
  'Linux',
  'Live2D',
  'LLM',
  'Machine Learning',
  'Magento',
  'Market research',
  'Maya',
  'MFC',
  'Microservices',
  'Microservices Architecture',
  'Microsoft Azure SQL Database',
  'Microsoft Dynamics 365',
  'Microsoft SQL Server',
  'Middleware',
  'MLOps',
  'Mobile Apps',
  'MongoDB',
  'MVC',
  'MVVM',
  'MySQL',
  'Neo4j',
  'NestJS',
  '.NET',
  '.Net Core',
  'NetSuite',
  'Networking',
  'NextJS',
  'Nginx',
  'NLP',
  'NodeJS',
  'NoSQL',
  'Nuxt.js',
  'Objective C',
  'Odoo',
  'OOP',
  'OpenCV',
  'Oracle',
  'OutSystems',
  'Pentest',
  'PHP',
  'Playwright',
  'PL/SQL',
  'PostgreSql',
  'Postman',
  'Power BI',
  'PQA',
  'Presale',
  'Product Design',
  'Product Management',
  'Product Metrics',
  'Product Owner',
  'Product roadmap',
  'Product strategy',
  'Project Management',
  'Prometheus',
  'Prompt Engineering',
  'Prototyping',
  'Python',
  'PyTorch',
  'QA QC',
  'Quarkus',
  'R',
  'ReactJS',
  'React Native',
  'Realm',
  'Redis',
  'Redux',
  'REST Assured',
  'Retrofit',
  'Risk Assessment / BCP',
  'Risk Management',
  'Robot Framework',
  'Robotic Process Automation (RPA)',
  'ROS2',
  'RPA',
  'RSpec',
  'Ruby',
  'Ruby on Rails',
  'Rust',
  'RxJS',
  'Salesforce',
  'SAP',
  'Sass',
  'Scala',
  'Scrum',
  'Security',
  'Security Hardening',
  'Selenium',
  'Shopify',
  'SIEM',
  'Sketch',
  'SLAM',
  'Smart contracts',
  'SOAP',
  'SOAR',
  'Software Architecture',
  'Solidity',
  'SOLID Principles',
  'Solution Architecture',
  'Spark',
  'Splunk',
  'Spring',
  'Spring Boot',
  'SQL',
  'SQLite',
  'SRS',
  'Stakeholder management',
  'Swift',
  'Symfony',
  'System Admin',
  'System Architecture',
  'Tableau',
  'Tailwind',
  'Team Management',
  'TensorFlow',
  'Terraform',
  'TestComplete',
  'Tester',
  'TestLink',
  'TestNG',
  'TestRail',
  'Trello',
  'TypeScript',
  'UI-UX',
  'UI / Visual Design',
  'Unit test',
  'Unity',
  'Unix',
  'Unreal Engine',
  'VBA',
  'vb.net',
  'VMware',
  'VueJS',
  'Vuex',
  'Web API',
  'White box testing',
  'Windows',
  'Windows PowerShell',
  'Windows Server',
  'WinForms',
  'Wireframing',
  'WooCommerce',
  'Wordpress',
  'WPF',
  'XML'
])
</script>
